# docker stack deploy -c docker-compose.yml bindman
version: '3.5'

services:

  bind:
    image: labbsr0x/dns-bind9
    volumes:
      - .bind9/data:/data
    networks:
      - network-bind
    ports:
    - "53:53/udp"
    - "53:53/tcp"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 2
        window: 5s

  bindman-dns-bind9:
    image: labbsr0x/bindman-dns-bind9
    volumes:
      - .bindman/data:/data
    ports:
      - 7070:7070
    depends_on:
      - bind
    networks:
      - network-bind
    environment:
      - BINDMAN_NAMESERVER_ADDRESS=bind
      - BINDMAN_NAMESERVER_KEY_FILE=Ktest.com.+157+04832.key
      - BINDMAN_NAMESERVER_ZONE=test.com
      - BINDMAN_DNS_REMOVAL_DELAY=1
      - BINDMAN_DEBUG=false

  bindman-dns-file-agent:
    image: labbsr0x/bindman-dns-file-agent
    depends_on:
      - bindman-dns-bind9
    volumes:
      - .agent:/data
    networks:
      - network-bind
    environment:
      - BINDMAN_DNS_MANAGER_ADDR=http://bindman-dns-bind9:7070
      - BINDMAN_DNS_REVERSE_PROXY_ADDR=0.0.0.0
      - BINDMAN_AGENT_CONFIG_PATH=/data/bindman_agent.json

networks:
  network-bind:
    external: true